---
title: "Research"
---

A complete list of my peer-reviewed (both non-archival and archival) publications are listed on this page.

## Archival

(@) Rena Li***, Sara Kingsley***, Chelsea Fan, Proteeti Sinha, Nora Wai, Jaimie Lee, Hong Shen, Motahhare Eslami, and Jason I. Hong. 2023. "Participation and Division of Labor in User-Driven Algorithm Audits: How Do Everyday Users Work together to Surface Algorithmic Harms?." In the Proceedings of ACM's Conference on Human Factors in Computing (CHI). Forthcoming, April 2023, Hamburg, Germany. [Paper link (https://github.com/sarakingsley/sarakingsley.github.io/blob/d8dc2a4095bec266363c3cf7e53d8de04db30d8f/twitterpaperindex.html) *** Equal contributions 

(@) `Sara Kingsley`, Proteeti Sinha, Clara Wang, Motahhare Eslami, and Jason I. Hong. 2022. "Give Everybody [..] a Little Bit More Equity": Content Creator Perspectives and Responses to the Algorithmic Demonetization of Content Associated with Disadvantaged Groups." Proc. ACM Hum.-Comput. Interact. 6, CSCW2, Article 424 (November 2022), 37 pages. [ACM Library](https://doi.org/10.1145/3555149) 

(@) Shamika Klassen, `Sara Kingsley`, Kalyn McCall, Joy Weinberg, and Casey Fiesler. 2022. Black Lives, Green Books, and Blue Checks: Comparing the Content of the Negro Motorist Green Book to the Content on Black Twitter. Proc. ACM Hum.-Comput. Interact. 6, GROUP, Article 27 (January 2022), 22 pages. [ACM Library](https://doi.org/10.1145/3492846 ) 

(@) Shamika Klassen, `Sara Kingsley`, Kalyn McCall, Joy Weinberg, and Casey Fiesler. 2021. More than a Modern Day Green Book: Exploring the Online Community of Black Twitter. Proc. ACM Hum.-Comput. Interact. 5, CSCW2, Article 458 (October 2021), 29 pages. [ACM Library](https://doi.org/10.1145/3479602)

(@) Rediet Abebe, Kehinde Aruleba, Abeba Birhane, `Sara Kingsley`, George Obaido, Sekou L. Remy, and Swathi Sadagopan.* 2021. Narratives and Counternarratives on Data Sharing in Africa. In Proceedings of the 2021 ACM Conference on Fairness, Accountability, and Transparency (FAccT '21). Association for Computing Machinery, New York, NY, USA, 329–341. [ACM Library](https://doi.org/10.1145/3442188.3445897) 

(@) `Sara Kingsley`, Mary L. Gray and Siddharth Suri. "Accounting for Market Frictions and Power Asymmetries in Online Labor Markets," Policy & Internet, 2015, 7 (4), 383-400. [Policy & Internet](https://ghostwork.info/wp-content/uploads/2019/02/marketfrictions.pdf)

## Non-archival
These publications were peer-reviewed by a non-publishing venue. I have posted these publications here via arXiv, SSRN and institutional press. 

(@) `Sara Kingsley`, Clara Wang, Alexandra Mikhalenko, Proteeti Sinha and Chinmay Kulkarni. "Auditing Digital Platforms for Discrimination in Economic Opportunity Advertising." In the Proceedings of ACM Economics and Computation 4th Workshop on Mechanism Design for Social Good (MD4SG 20), June 2019: Phoenix, Arizona. [arXiv](https://arxiv.org/abs/2008.09656)

(@) Abhishek Gupta, Camylle Lanteigne and `Sara Kingsley`. "SECure: A Social and Environmental Certificate for AI Systems." In the Proceedings of ACM Economics and Computation 4th Workshop on Mechanism Design for Social Good (MD4SG 20), June 2019: Phoenix, Arizona. [arXiv](https://arxiv.org/abs/2006.06217) 	

(@) `Sara Kingsley`, Mary L. Gray and Siddharth Suri. "Monopsony and the crowd: labor for lemons?" Conference on Internet, Policy &. Policy (IPP), September 2014: Oxford Internet Institute, Oxford University, Oxford. [Oxford University](http://blogs.oii.ox.ac.uk/ipp-conference/sites/ipp/files/documents/Monopsony_and_theCrowd_SCK_MLG_SS.pdf)



## Policy Papers
These papers were written for policy stakeholders and are not peer-reviewed.  

`forthcoming`


## Working Papers
These papers are works in progress and are not yet peer-reviewed. I have posted these publications here via arXiv. 

* `Sara Kingsley`. "A Cognitive Science perspective for learning how to design
meaningful user experiences and human-centered technology." May 2020. [arXiv](https://arxiv.org/pdf/2106.07553.pdf)
